# Generated by Django 5.0.1 on 2024-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_address', models.CharField(max_length=100, null=True)),
                ('current_address_proof', models.ImageField(null=True, upload_to='address_proofs/')),
                ('permanent_address', models.CharField(max_length=100, null=True)),
                ('permanent_address_proof', models.ImageField(null=True, upload_to='address_proofs/')),
                ('remark', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_number', models.IntegerField(null=True)),
                ('account_holder_name', models.CharField(max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=11, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('check_image', models.ImageField(null=True, upload_to='checks/')),
                ('remark', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=300, null=True)),
                ('proposal_amt', models.IntegerField(null=True)),
                ('approved_amt', models.IntegerField(null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('pan_number', models.CharField(max_length=10, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
