# Generated by Django 4.2.6 on 2024-02-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
